name = "tube-gist"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "tube-gist-db"
database_id = "86552a09-0e91-406c-8ce5-ccf38d26a4e9"
